version: '3'

services:
  goapp:
    build: .
    volumes: 
      - .:/app
  mysql-go-intensivo:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:  # Corrigido para 'environment' ao invés de 'enviroments'
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: orders
      MYSQL_PASSWORD: root
    volumes:
      - ./.docker/mysql:/var/lib/mysql
